version: '3'
services:
  proxy:
    image: nginx:latest
    depends_on:
      - web0
      - web1
      - echo0
      - echo1
      - node0
      - node1
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  echo0:
    image: gihyodocker/echo:latest
    expose:
      - "8080"
  echo1:
    image: gihyodocker/echo:latest
    expose:
      - "8080"
  node0:
    build:
      context: nodejs
      dockerfile: Dockerfile
    image: node_server:latest
    expose:
      - "3000"
  node1:
    build:
      context: nodejs
      dockerfile: Dockerfile
    image: node_server:latest
    expose:
      - "3000"
  web0:
    image: nginx:latest
    depends_on:
      - php
    expose:
      - "8080"
    volumes:
      - ./source:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  web1:
    image: nginx:latest
    depends_on:
      - php
    expose:
      - "8080"
    volumes:
      - ./source:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.3-fpm
    expose:
      - "9000"
    volumes:
      - ./source:/source
