version: '3'
services:
  proxy:
    image: nginx:latest
    depends_on:
      - app0
      - app1
      - web0
      - web1
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  app0:
    image: gihyodocker/echo:latest
    expose:
      - "8080"
  app1:
    image: gihyodocker/echo:latest
    expose:
      - "8080"
  web0:
    image: nginx:latest
    depends_on:
      - php
    expose:
      - "8080"
    volumes:
      - ./source:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  web1:
    image: nginx:latest
    depends_on:
      - php
    expose:
      - "8080"
    volumes:
      - ./source:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.3-fpm
    expose:
      - "9000"
    volumes:
      - ./source:/source
